### ISSUE TITLE
invalid syntax error for joblib.dump() statement

### ISSUE THREAD

**Issue by shantanu9** [abhishekkrthakur/e01#1]
Hi  @abhishekkrthakur ,  

I am following your machine learning series on youtube by writing each and every piece of code by myself for better understanding.

[src.zip](https://github.com/abhishekkrthakur/e01/files/4027123/src.zip)

Facing the syntax error for joblib statement even though I followed the exactly what you taught. 

![image](https://user-images.githubusercontent.com/14205178/71835488-b5895680-30d7-11ea-8379-bbfdd119056e.png)

![image](https://user-images.githubusercontent.com/14205178/71835381-6ba07080-30d7-11ea-9e9d-bb5c86af28df.png)

I know this must be something very silly, but couldn't fix it. Hoping you could help me.

**Comment by abhishekkrthakur** [comment]
Hi @shantanu9 , which python version do you have? Please note that I work on 3.7 version of python and all videos will follow that.

Also, this repository will no longer be updated with new videos, please take a look at https://github.com/abhishekkrthakur/mlframework which will be updated with every new video :)

**Comment by shantanu9** [comment]
Thanks Abhishek for your response. 

I will update the python version to 3.7. Currently, I am using 3.4 version of python.

And, thanks for informing about the new respository. I will continue to follow the new.
